// 中国历代科举状元籍贯数据（含生平信息）
// 自动从 index.html 同步生成

const ZHUANGYUAN_DATA = const _RAW = [
  // ── 隋 ──
  { name:"孙伏伽", dynasty:"隋", year:605, province:"河北", city:"衡水市", county:"故城县", uncertain:true, bio:"孙伏伽（？—658年），字元规，唐代初期官员。早在隋朝大业年间（605年）考中进士，后入唐为官，武德五年（622年）再次考中进士第一名。历任御史大夫、大理卿等职，以直言敢谏著称。《登科记考》称其为第一甲第一名，但关于其是否为'隋朝状元'尚存争议。" },

  // ── 唐 ──
  { name:"孙伏伽",   dynasty:"唐", year:622, province:"河北", city:"衡水市", county:"故城县", bio:"孙伏伽（？—658年），字元规，贝州武城（今河北故城）人。武德五年以进士第一及第，是唐朝第一科状元。历任大理卿、御史大夫等职，以直言敢谏著称，唐太宗曾赞其'诚直'。" },
  { name:"侯君素",   dynasty:"唐", year:623, province:"河南", city:"洛阳市", uncertain:true },
  { name:"郭元振",   dynasty:"唐", year:670, province:"河北", city:"邯郸市", county:"大名县", bio:"郭元振（656—713年），名震，字元振，魏州贵乡（今河北大名）人。唐朝名将、宰相。咸亨元年（670年）进士第一及第。历任凉州都督、安西大都护、兵部尚书、同中书门下三品。在西北边境多有建树，封代国公。" },
  { name:"员半千",   dynasty:"唐", year:672, province:"山西", city:"临汾市", county:"洪洞县" },
  { name:"贺知章",   dynasty:"唐", year:695, province:"浙江", city:"杭州市", county:"萧山区", bio:"贺知章（659—744年），字季真，越州永兴（今浙江杭州萧山）人。唐代著名诗人、书法家。证圣元年（695年）进士第一及第。历任太常博士、礼部侍郎、太子宾客、秘书监。其诗作《咏柳》《回乡偶书》传诵千古。书法以草隶见长。为人旷达豪放，晚年自号'四明狂客'。" },
  { name:"王翰",     dynasty:"唐", year:710, province:"山西", city:"太原市", bio:"王翰（687—726年），字子羽，并州晋阳（今山西太原）人。唐代诗人。景云元年（710年）进士第一及第。代表作《凉州词》'葡萄美酒夜光杯'为千古名篇。" },
  { name:"席豫",     dynasty:"唐", year:710, province:"陕西", city:"西安市" },
  { name:"王维",     dynasty:"唐", year:721, province:"山西", city:"运城市", county:"永济市", bio:"王维（701—761年），字摩诘，号摩诘居士，蒲州（今山西永济）人。开元九年（721年）进士第一及第。唐代著名诗人、画家，官至尚书右丞。其诗以山水田园诗著称，被誉为'诗中有画，画中有诗'。与孟浩然合称'王孟'，是唐代山水田园诗派代表人物。" },
  { name:"苗晋卿",   dynasty:"唐", year:723, province:"山西", city:"长治市", county:"壶关县" },
  { name:"李昂",     dynasty:"唐", year:724, province:"陕西", city:"西安市", uncertain:true },
  { name:"祖咏",     dynasty:"唐", year:724, province:"河南", city:"洛阳市" },
  { name:"储光羲",   dynasty:"唐", year:726, province:"江苏", city:"镇江市", county:"丹阳市" },
  { name:"王昌龄",   dynasty:"唐", year:727, province:"山西", city:"太原市", uncertain:true, bio:"王昌龄（698—757年），字少伯，太原（今山西太原）人。唐代著名边塞诗人。其进士身份及是否状元存在史料争议。代表作有《出塞》'秦时明月汉时关'、'一片冰心在玉壶'等名句。世称'七绝圣手'。" },
  { name:"崔曙",     dynasty:"唐", year:729, province:"河南", city:"商丘市" },
  { name:"卢象",     dynasty:"唐", year:729, province:"河南", city:"济南市" },
  { name:"刘晏",     dynasty:"唐", year:730, province:"山东", city:"菏泽市" },
  { name:"萧颖士",   dynasty:"唐", year:735, province:"安徽", city:"阜阳市" },
  { name:"李华",     dynasty:"唐", year:735, province:"河北", city:"衡水市" },
  { name:"颜真卿",   dynasty:"唐", year:734, province:"陕西", city:"西安市", bio:"颜真卿（709—784年），字清臣，京兆万年（今陕西西安）人。唐代著名书法家、忠臣。开元二十二年（734年）进士第一及第。历任平原太守、刑部尚书、太子太师，封鲁郡公。安史之乱中率兵抵抗。书法与柳公权并称'颜筋柳骨'，创'颜体'楷书，代表作有《多宝塔碑》《颜勤礼碑》等。" },
  { name:"刘长卿",   dynasty:"唐", year:733, province:"安徽", city:"宣城市", uncertain:true },
  { name:"杜鸿渐",   dynasty:"唐", year:740, province:"河南", city:"濮阳市" },
  { name:"李嶷",     dynasty:"唐", year:741, province:"陕西", city:"西安市" },
  { name:"李揆",     dynasty:"唐", year:741, province:"陕西", city:"西安市" },
  { name:"严武",     dynasty:"唐", year:751, province:"陕西", city:"西安市" },
  { name:"张继",     dynasty:"唐", year:753, province:"湖北", city:"襄阳市", uncertain:true, bio:"张继（约715—约779年），字懿孙，襄州（今湖北襄阳）人。唐代诗人。其状元身份存在争议。以《枫桥夜泊》'月落乌啼霜满天，江枫渔火对愁眠'闻名千古。" },
  { name:"元结",     dynasty:"唐", year:754, province:"河南", city:"洛阳市" },
  { name:"独孤及",   dynasty:"唐", year:754, province:"河南", city:"洛阳市" },
  { name:"杨炎",     dynasty:"唐", year:756, province:"陕西", city:"宝鸡市" },
  { name:"鲁收",     dynasty:"唐", year:756, province:"山西", city:"太原市" },
  { name:"常衮",     dynasty:"唐", year:757, province:"陕西", city:"西安市" },
  { name:"梁肃",     dynasty:"唐", year:773, province:"河南", city:"平顶山市" },
  { name:"权德舆",   dynasty:"唐", year:779, province:"陕西", city:"宝鸡市" },
  { name:"崔元翰",   dynasty:"唐", year:786, province:"河南", city:"保定市" },
  { name:"张正元",   dynasty:"唐", year:797, province:"河南", city:"南阳市" },
  { name:"李程",     dynasty:"唐", year:798, province:"陕西", city:"西安市" },
  { name:"白居易",   dynasty:"唐", year:800, province:"陕西", city:"渭南市", bio:"白居易（772—846年），字乐天，号香山居士，下邽（今陕西渭南）人。唐代著名诗人。贞元十六年（800年）进士第一及第。其是否为明经科或进士科状元存在争议。历任翰林学士、左拾遗、江州司马、杭州刺史、苏州刺史、刑部尚书。倡导新乐府运动，代表作有《长恨歌》《琵琶行》《卖炭翁》等。与元稹并称'元白'。" },
  { name:"沈传师",   dynasty:"唐", year:800, province:"浙江", city:"湖州市" },
  { name:"裴度",     dynasty:"唐", year:793, province:"陕西", city:"运城市" },
  { name:"吕温",     dynasty:"唐", year:796, province:"河南", city:"洛阳市" },
  { name:"韩愈",     dynasty:"唐", year:792, province:"河南", city:"焦作市", county:"孟州市", bio:"韩愈（768—824年），字退之，河南河阳（今河南孟州）人。唐代文学家、思想家。郡望昌黎，世称韩昌黎。贞元八年（792年）进士第一及第。官至吏部侍郎。古文运动领袖，'唐宋八大家'之首。代表作《师说》《进学解》《祭十二郎文》等。苏轼赞其'文起八代之衰'。" },
  { name:"欧阳詹",   dynasty:"唐", year:792, province:"福建", city:"泉州市" },
  { name:"王涯",     dynasty:"唐", year:793, province:"山西", city:"太原市" },
  { name:"冯宿",     dynasty:"唐", year:793, province:"浙江", city:"金华市" },
  { name:"刘禹锡",   dynasty:"唐", year:793, province:"河南", city:"洛阳市", bio:"刘禹锡（772—842年），字梦得，洛阳（今河南洛阳）人。唐代文学家、哲学家。贞元九年（793年）进士第一及第。历任监察御史、郎州司马、连州刺史、太子宾客等职。与白居易并称'刘白'。代表作《陋室铭》《竹枝词》《乌衣巷》等，有'诗豪'之称。" },
  { name:"柳宗元",   dynasty:"唐", year:793, province:"山西", city:"运城市", county:"永济市", bio:"柳宗元（773—819年），字子厚，河东（今山西永济）人。唐代文学家、哲学家。贞元九年（793年）进士第一及第。官至柳州刺史，世称柳河东、柳柳州。'唐宋八大家'之一，与韩愈共同倡导古文运动。代表作《永州八记》《捕蛇者说》《江雪》等。" },
  { name:"崔群",     dynasty:"唐", year:796, province:"山东", city:"德州市" },
  { name:"王起",     dynasty:"唐", year:796, province:"山东", city:"临沂市" },
  { name:"李绅",     dynasty:"唐", year:796, province:"浙江", city:"湖州市", county:"吴兴区", bio:"李绅（772—846年），字公垂，湖州乌程（今浙江湖州）人。唐代诗人。元和元年（806年）进士，其状元身份存疑。官至宰相。代表作《悯农》'锄禾日当午，汗滴禾下土'为千古传诵。" },
  { name:"令狐楚",   dynasty:"唐", year:793, province:"山西", city:"西安市" },
  { name:"张又新",   dynasty:"唐", year:809, province:"陕西", city:"西安市" },
  { name:"牛僧孺",   dynasty:"唐", year:808, province:"陕西", city:"西安市" },
  { name:"柳公权",   dynasty:"唐", year:808, province:"陕西", city:"铜川市", county:"耀州区", bio:"柳公权（778—865年），字诚悬，京兆华原（今陕西铜川耀州）人。唐代著名书法家。元和三年（808年）进士第一及第。官至太子少师。书法创'柳体'楷书，与颜真卿并称'颜筋柳骨'。代表作《玄秘塔碑》《神策军碑》等。" },
  { name:"元稹",     dynasty:"唐", year:809, province:"河南", city:"洛阳市", bio:"元稹（779—831年），字微之，洛阳（今河南洛阳）人。唐代诗人、文学家。元和元年（806年）进士第一及第。官至同中书门下平章事（宰相）。与白居易并称'元白'，共同倡导新乐府运动。代表作《菊花》《离思》'曾经沧海难为水'等。所作传奇《莺莺传》对后世影响深远。" },
  { name:"章孝标",   dynasty:"唐", year:810, province:"浙江", city:"杭州市" },
  { name:"裴休",     dynasty:"唐", year:825, province:"河南", city:"济源市" },
  { name:"归仁绍",   dynasty:"唐", year:824, province:"江苏", city:"苏州市" },
  { name:"韦瓘",     dynasty:"唐", year:836, province:"陕西", city:"西安市" },
  { name:"杜牧",     dynasty:"唐", year:828, province:"陕西", city:"西安市", bio:"杜牧（803—852年），字牧之，京兆万年（今陕西西安）人。唐代著名诗人。大和二年（828年）进士第一及第。官至中书舍人。其诗以七绝见长，风格俊爽清丽，与李商隐并称'小李杜'。代表作《阿房宫赋》《山行》《清明》《泊秦淮》等。" },
  { name:"李商隐",   dynasty:"唐", year:838, province:"河南", city:"郑州市", county:"荥阳市", uncertain:true, bio:"李商隐（约813—约858年），字义山，号玉溪生，怀州河内（今河南沁阳，一说荥阳）人。唐代著名诗人。开成二年（837年）进士，其状元身份存疑。与杜牧合称'小李杜'。其诗构思新奇，风格秾丽，尤其无题诗缠绵悱恻，代表作《锦瑟》《夜雨寄北》《乐游原》等。" },
  { name:"卢肇",     dynasty:"唐", year:836, province:"江西", city:"宜春市" },
  { name:"许浑",     dynasty:"唐", year:832, province:"江苏", city:"镇江市" },
  { name:"赵嘏",     dynasty:"唐", year:840, province:"江苏", city:"淮安市" },
  { name:"马戴",     dynasty:"唐", year:840, province:"山西", city:"临汾市" },
  { name:"温庭筠",   dynasty:"唐", year:848, province:"山西", city:"太原市", uncertain:true, bio:"温庭筠（812—约866年），本名岐，字飞卿，太原（今山西太原）人。唐代诗人、词人。其状元身份存疑。精通音律，诗词并工，为'花间派'代表词人。诗与李商隐齐名，时称'温李'。代表作《商山早行》'鸡声茅店月，人迹板桥霜'" },
  { name:"李频",     dynasty:"唐", year:851, province:"浙江", city:"杭州市" },
  { name:"崔铉",     dynasty:"唐", year:837, province:"山东", city:"济南市" },
  { name:"郑颢",     dynasty:"唐", year:842, province:"河南", city:"郑州市" },
  { name:"崔慎由",   dynasty:"唐", year:837, province:"山东", city:"济南市" },
  { name:"封敖",     dynasty:"唐", year:825, province:"陕西", city:"西安市" },
  { name:"裴坦",     dynasty:"唐", year:848, province:"陕西", city:"西安市" },
  { name:"司空图",   dynasty:"唐", year:862, province:"陕西", city:"渭南市" },
  { name:"卢携",     dynasty:"唐", year:855, province:"河南", city:"商丘市" },
  { name:"崔安潜",   dynasty:"唐", year:854, province:"山东", city:"济南市" },
  { name:"崔瀣",     dynasty:"唐", year:855, province:"山东", city:"济南市" },
  { name:"崔昭纬",   dynasty:"唐", year:859, province:"山东", city:"济南市" },
  { name:"路岩",     dynasty:"唐", year:850, province:"山西", city:"西安市" },
  { name:"张读",     dynasty:"唐", year:850, province:"山东", city:"临沂市" },
  { name:"归仁泽",   dynasty:"唐", year:860, province:"江苏", city:"苏州市" },
  { name:"孔纁",     dynasty:"唐", year:866, province:"山东", city:"曲阜市" },
  { name:"崔渊",     dynasty:"唐", year:866, province:"山东", city:"济南市" },
  { name:"崔砺",     dynasty:"唐", year:896, province:"山东", city:"济南市" },
  { name:"崔昭",     dynasty:"唐", year:900, province:"山东", city:"济南市" },
  { name:"崔沆",     dynasty:"唐", year:871, province:"山东", city:"济南市" },
  { name:"黄颇",     dynasty:"唐", year:876, province:"江西", city:"宜春市" },
  { name:"归黯",     dynasty:"唐", year:877, province:"江苏", city:"苏州市" },
  { name:"崔澹",     dynasty:"唐", year:878, province:"山东", city:"济南市" },
  { name:"孙偓",     dynasty:"唐", year:880, province:"山东", city:"济南市" },
  { name:"卢汝弼",   dynasty:"唐", year:864, province:"河南", city:"商丘市" },
  { name:"翁彦枢",   dynasty:"唐", year:895, province:"福建", city:"福州市" },
  { name:"钟辐",     dynasty:"唐", year:895, province:"江西", city:"吉安市" },
  { name:"卢延让",   dynasty:"唐", year:893, province:"山西", city:"太原市" },
  { name:"韦庄",     dynasty:"唐", year:894, province:"陕西", city:"西安市" },
  { name:"郑谷",     dynasty:"唐", year:880, province:"江西", city:"宜春市" },
  { name:"罗隐",     dynasty:"唐", year:870, province:"浙江", city:"杭州市", county:"富阳区", uncertain:true, bio:"罗隐（833—909年），字昭谏，杭州新城（今浙江杭州富阳）人。唐代文学家。其状元身份存疑。诗文俱佳，尤以讽刺小品文著称。著有《谗书》，其诗《蜂》'不论平地与山尖'为传世名篇。" },
  { name:"柳玭",     dynasty:"唐", year:880, province:"陕西", city:"西安市" },
  { name:"陈乂",     dynasty:"唐", year:885, province:"福建", city:"福州市" },
  { name:"孙祁",     dynasty:"唐", year:902, province:"山东", city:"济南市" },
  { name:"赵观文",   dynasty:"唐", year:899, province:"广西", city:"桂林市", county:"临桂区" },
  { name:"裴格",     dynasty:"唐", year:886, province:"陕西", city:"西安市" },
  { name:"归系",     dynasty:"唐", year:899, province:"江苏", city:"苏州市" },
  { name:"卢文焕",   dynasty:"唐", year:894, province:"河南", city:"洛阳市" },
  { name:"韩渥",     dynasty:"唐", year:890, province:"河南", city:"洛阳市" },
  { name:"曹松",     dynasty:"唐", year:901, province:"安徽", city:"合肥市" },
  { name:"柯崇",     dynasty:"唐", year:901, province:"福建", city:"泉州市" },
  { name:"裴延翰",   dynasty:"唐", year:904, province:"山西", city:"西安市" },

  // ── 五代十国 ──
  { name:"冯道",     dynasty:"五代十国", year:916, province:"河北", city:"沧州市", uncertain:true },
  { name:"和凝",     dynasty:"五代十国", year:920, province:"山东", city:"聊城市" },
  { name:"崔棁",     dynasty:"五代十国", year:928, province:"山东", city:"济南市" },
  { name:"王仁裕",   dynasty:"五代十国", year:924, province:"甘肃", city:"天水市", uncertain:true },
  { name:"桑维翰",   dynasty:"五代十国", year:930, province:"河南", city:"洛阳市" },
  { name:"窦仪",     dynasty:"五代十国", year:937, province:"河北", city:"沧州市" },
  { name:"徐铉",     dynasty:"五代十国", year:940, province:"江苏", city:"南京市", uncertain:true },
  { name:"李昉",     dynasty:"五代十国", year:947, province:"河北", city:"衡水市" },
  { name:"王溥",     dynasty:"五代十国", year:954, province:"山西", city:"太原市" },
  { name:"扈蒙",     dynasty:"五代十国", year:956, province:"山东", city:"德州市" },
  { name:"卢多逊",   dynasty:"五代十国", year:958, province:"河南", city:"洛阳市" },

  // ── 北宋 ──
  { name:"王嗣宗",   dynasty:"北宋", year:976, province:"山西", city:"太原市" },
  { name:"吕蒙正",   dynasty:"北宋", year:977, province:"河南", city:"洛阳市", bio:"吕蒙正（944—1011年），字圣功，河南洛阳人。太平兴国二年（977年）进士第一及第。北宋著名宰相，三度拜相。以知人善任著称，提拔了富弼、张齐贤等名臣。为人宽厚正直，是宋代贤相的代表人物之一。" },
  { name:"李沆",     dynasty:"北宋", year:977, province:"河北", city:"邯郸市" },
  { name:"宋湜",     dynasty:"北宋", year:979, province:"山东", city:"济南市" },
  { name:"胡旦",     dynasty:"北宋", year:978, province:"山东", city:"济南市" },
  { name:"梁灏",     dynasty:"北宋", year:980, province:"山东", city:"泰安市" },
  { name:"陈充",     dynasty:"北宋", year:985, province:"四川", city:"成都市" },
  { name:"苏易简",   dynasty:"北宋", year:988, province:"四川", city:"成都市" },
  { name:"陈尧叟",   dynasty:"北宋", year:988, province:"四川", city:"南充市", bio:"陈尧叟（961—1017年），字唐夫，阆州阆中（今四川南充阆中）人。端拱二年（989年）进士第一及第。官至同平章事（宰相）。与其弟陈尧佐、陈尧咨皆进士出身，时称'三陈'。曾主持编纂《册府元龟》。" },
  { name:"孙何",     dynasty:"北宋", year:995, province:"河南", city:"郑州市" },
  { name:"姜盖",     dynasty:"北宋", year:997, province:"河南", city:"南阳市" },
  { name:"李迪",     dynasty:"北宋", year:1000, province:"山东", city:"济南市" },
  { name:"王曾",     dynasty:"北宋", year:1000, province:"山东", city:"济南市" },
  { name:"陈尧咨",   dynasty:"北宋", year:1000, province:"四川", city:"南充市", bio:"陈尧咨（970—1034年），字嘉谟，阆州阆中（今四川南充阆中）人。咸平三年（1000年）进士第一及第。陈尧叟之弟，兄弟皆状元。擅长书法、射箭。欧阳修《卖油翁》即以其射箭轶事为题材。官至武信军节度使。" },
  { name:"张观",     dynasty:"北宋", year:1002, province:"河南", city:"焦作市" },
  { name:"蔡齐",     dynasty:"北宋", year:1015, province:"山东", city:"青岛市" },
  { name:"韩国华",   dynasty:"北宋", year:979, province:"陕西", city:"西安市" },
  { name:"宋庠",     dynasty:"北宋", year:1024, province:"安徽", city:"郑州市" },
  { name:"王尧臣",   dynasty:"北宋", year:1025, province:"湖北", city:"武汉市" },
  { name:"张唐英",   dynasty:"北宋", year:1049, province:"四川", city:"成都市" },
  { name:"冯京",     dynasty:"北宋", year:1051, province:"湖北", city:"武汉市" },
  { name:"章衡",     dynasty:"北宋", year:1057, province:"福建", city:"南平市" },
  { name:"贾黯",     dynasty:"北宋", year:1034, province:"河南", city:"南阳市" },
  { name:"许将",     dynasty:"北宋", year:1063, province:"福建", city:"福州市" },
  { name:"郑獬",     dynasty:"北宋", year:1063, province:"湖北", city:"武汉市" },
  { name:"彭汝砺",   dynasty:"北宋", year:1067, province:"江西", city:"上饶市" },
  { name:"余中",     dynasty:"北宋", year:1073, province:"浙江", city:"杭州市" },
  { name:"叶祖洽",   dynasty:"北宋", year:1073, province:"福建", city:"南平市" },
  { name:"徐铎",     dynasty:"北宋", year:1077, province:"福建", city:"莆田市" },
  { name:"黄裳",     dynasty:"北宋", year:1082, province:"福建", city:"南平市" },
  { name:"时彦",     dynasty:"北宋", year:1088, province:"河南", city:"郑州市" },
  { name:"焦蹈",     dynasty:"北宋", year:1091, province:"河南", city:"芜湖市" },
  { name:"毕渐",     dynasty:"北宋", year:1097, province:"湖北", city:"武汉市" },
  { name:"何昌言",   dynasty:"北宋", year:1100, province:"福建", city:"南昌市" },
  { name:"霍端友",   dynasty:"北宋", year:1103, province:"安徽", city:"常州市" },
  { name:"蔡薿",     dynasty:"北宋", year:1106, province:"福建", city:"开封市" },
  { name:"王昂",     dynasty:"北宋", year:1109, province:"福建", city:"福州市" },
  { name:"莫俦",     dynasty:"北宋", year:1112, province:"浙江", city:"湖州市" },
  { name:"沈晦",     dynasty:"北宋", year:1121, province:"浙江", city:"湖州市" },
  { name:"王悦",     dynasty:"北宋", year:1115, province:"河南", city:"洛阳市" },

  // ── 南宋 ──
  { name:"张九成",   dynasty:"南宋", year:1132, province:"浙江", city:"杭州市", bio:"张九成（1092—1159年），字子韶，钱塘（今浙江杭州）人。绍兴二年（1132年）进士第一及第。理学家，官至刑部侍郎。因反对秦桧议和，被贬谪。著有《横浦集》。" },
  { name:"刘才邵",   dynasty:"南宋", year:1135, province:"浙江", city:"杭州市" },
  { name:"汪应辰",   dynasty:"南宋", year:1138, province:"江西", city:"玉山县" },
  { name:"黄公度",   dynasty:"南宋", year:1148, province:"福建", city:"莆田市" },
  { name:"张孝祥",   dynasty:"南宋", year:1151, province:"安徽", city:"芜湖市", bio:"张孝祥（1132—1170年），字安国，号于湖居士，历阳乌江（今安徽和县/芜湖）人。南宋著名豪放派词人。绍兴二十四年（1154年）进士第一及第。历任中书舍人、显谟阁直学士。词风豪放，代表作《念奴娇·过洞庭》《六州歌头》等。" },
  { name:"王十朋",   dynasty:"南宋", year:1151, province:"浙江", city:"温州市", county:"乐清市", bio:"王十朋（1112—1171年），字龟龄，号梅溪，温州乐清（今浙江乐清）人。南宋名臣、文学家。绍兴二十七年（1157年）进士第一及第。官至龙图阁学士。以直言敢谏著称，力主抗金。著有《梅溪集》。" },
  { name:"施师点",   dynasty:"南宋", year:1151, province:"浙江", city:"杭州市" },
  { name:"梁克家",   dynasty:"南宋", year:1157, province:"福建", city:"泉州市" },
  { name:"萧国梁",   dynasty:"南宋", year:1160, province:"福建", city:"福州市" },
  { name:"郑侨",     dynasty:"南宋", year:1162, province:"福建", city:"莆田市" },
  { name:"木待问",   dynasty:"南宋", year:1166, province:"浙江", city:"温州市" },
  { name:"赵汝愚",   dynasty:"南宋", year:1168, province:"浙江", city:"杭州市" },
  { name:"郑汝谐",   dynasty:"南宋", year:1169, province:"浙江", city:"金华市" },
  { name:"詹骙",     dynasty:"南宋", year:1172, province:"福建", city:"绍兴市" },
  { name:"黄定",     dynasty:"南宋", year:1175, province:"福建", city:"福州市" },
  { name:"姚颖",     dynasty:"南宋", year:1178, province:"浙江", city:"宁波市" },
  { name:"曾逮",     dynasty:"南宋", year:1181, province:"江西", city:"赣州市" },
  { name:"黄由",     dynasty:"南宋", year:1184, province:"浙江", city:"温州市" },
  { name:"余复",     dynasty:"南宋", year:1187, province:"福建", city:"宁波市" },
  { name:"卫泾",     dynasty:"南宋", year:1187, province:"江苏", city:"苏州市" },
  { name:"陈亮",     dynasty:"南宋", year:1193, province:"浙江", city:"金华市", county:"永康市", bio:"陈亮（1143—1194年），字同甫，号龙川，婺州永康（今浙江永康）人。南宋著名思想家、文学家。绍熙四年（1193年）进士第一及第。永康学派创始人，提倡事功之学，反对空谈性理。词作雄浑豪放，与辛弃疾交厚。著有《龙川文集》。" },
  { name:"邹应龙",   dynasty:"南宋", year:1196, province:"福建", city:"福州市" },
  { name:"任希夷",   dynasty:"南宋", year:1196, province:"四川", city:"成都市" },
  { name:"毛自知",   dynasty:"南宋", year:1199, province:"浙江", city:"衢州市" },
  { name:"郑性之",   dynasty:"南宋", year:1205, province:"福建", city:"福州市" },
  { name:"郑乔年",   dynasty:"南宋", year:1202, province:"福建", city:"宁德市" },
  { name:"蒋重珍",   dynasty:"南宋", year:1211, province:"江苏", city:"无锡市" },
  { name:"吴潜",     dynasty:"南宋", year:1208, province:"安徽", city:"芜湖市" },
  { name:"袁甫",     dynasty:"南宋", year:1208, province:"浙江", city:"宁波市" },
  { name:"阳枋",     dynasty:"南宋", year:1220, province:"四川", city:"重庆市" },
  { name:"吴叔告",   dynasty:"南宋", year:1223, province:"福建", city:"莆田市" },
  { name:"李道传",   dynasty:"南宋", year:1223, province:"四川", city:"成都市" },
  { name:"刘渭",     dynasty:"南宋", year:1214, province:"福建", city:"金华市" },
  { name:"赵建大",   dynasty:"南宋", year:1217, province:"浙江", city:"温州市" },
  { name:"徐元杰",   dynasty:"南宋", year:1229, province:"江西", city:"上饶市" },
  { name:"周坦",     dynasty:"南宋", year:1232, province:"安徽", city:"温州市" },
  { name:"留梦炎",   dynasty:"南宋", year:1241, province:"浙江", city:"衢州市" },
  { name:"徐俨夫",   dynasty:"南宋", year:1244, province:"福建", city:"温州市" },
  { name:"姚勉",     dynasty:"南宋", year:1247, province:"江西", city:"宜春市" },
  { name:"方山京",   dynasty:"南宋", year:1247, province:"浙江", city:"宁波市" },
  { name:"吴必大",   dynasty:"南宋", year:1250, province:"江西", city:"吉安市" },
  { name:"周震炎",   dynasty:"南宋", year:1253, province:"湖南", city:"湘潭市" },
  { name:"方逢辰",   dynasty:"南宋", year:1253, province:"浙江", city:"杭州市" },
  { name:"文天祥",   dynasty:"南宋", year:1256, province:"江西", city:"吉安市", county:"吉安县", bio:"文天祥（1236—1283年），字宋瑞，一字履善，号文山，吉州庐陵（今江西吉安）人。南宋末年著名民族英雄、文学家。宝祐四年（1256年）进士第一及第。官至右丞相兼枢密使。元军南侵时组织抗元，兵败被俘。在狱中作《正气歌》《过零丁洋》'人生自古谁无死，留取丹心照汗青'等名篇。从容就义，是中华民族气节的象征。" },
  { name:"蒋元龙",   dynasty:"南宋", year:1256, province:"浙江", city:"杭州市" },
  { name:"马廷鸾",   dynasty:"南宋", year:1254, province:"安徽", city:"池州市" },
  { name:"汪立信",   dynasty:"南宋", year:1259, province:"安徽", city:"池州市" },
  { name:"陈文龙",   dynasty:"南宋", year:1268, province:"福建", city:"莆田市" },
  { name:"陈仁玉",   dynasty:"南宋", year:1268, province:"浙江", city:"台州市" },
  { name:"张镇孙",   dynasty:"南宋", year:1271, province:"广东", city:"广州市" },
  { name:"俞国宝",   dynasty:"南宋", year:1274, province:"浙江", city:"杭州市" },
  { name:"刘鼎孙",   dynasty:"南宋", year:1274, province:"浙江", city:"温州市" },

  // ── 辽 ──
  { name:"吕德懋",   dynasty:"辽", year:983, province:"河北", uncertain:true },
  { name:"张干",     dynasty:"辽", year:986, province:"河北", uncertain:true },
  { name:"刘二玄",   dynasty:"辽", year:993, province:"河北", uncertain:true },
  { name:"王熙",     dynasty:"辽", year:999, province:"不详", uncertain:true },
  { name:"张毂",     dynasty:"辽", year:1006, province:"河北", uncertain:true },

  // ── 金 ──
  { name:"胡砺",     dynasty:"金", year:1128, province:"河北" },
  { name:"刘撝",     dynasty:"金", year:1135, province:"河南" },
  { name:"蔡珪",     dynasty:"金", year:1138, province:"河北" },
  { name:"张汇",     dynasty:"金", year:1148, province:"河北" },
  { name:"孟宗献",   dynasty:"金", year:1151, province:"河南" },
  { name:"徒单恭",   dynasty:"金", year:1154, province:"不详" },
  { name:"张行信",   dynasty:"金", year:1160, province:"河南" },
  { name:"移剌慥",   dynasty:"金", year:1163, province:"不详" },
  { name:"粘合南合", dynasty:"金", year:1166, province:"不详" },
  { name:"张端",     dynasty:"金", year:1169, province:"河南" },
  { name:"刘仲渊",   dynasty:"金", year:1172, province:"山东" },
  { name:"李邦直",   dynasty:"金", year:1175, province:"山东" },
  { name:"赵永吉",   dynasty:"金", year:1178, province:"河南" },
  { name:"王彦昂",   dynasty:"金", year:1181, province:"山西" },
  { name:"杨建安",   dynasty:"金", year:1184, province:"山东" },
  { name:"张行信",   dynasty:"金", year:1187, province:"河北" },
  { name:"完颜匡",   dynasty:"金", year:1190, province:"不详" },
  { name:"赵讽",     dynasty:"金", year:1193, province:"河南" },
  { name:"刘炳",     dynasty:"金", year:1196, province:"山东" },
  { name:"任熊祥",   dynasty:"金", year:1199, province:"山西" },
  { name:"冯延登",   dynasty:"金", year:1202, province:"山东" },
  { name:"王若虚",   dynasty:"金", year:1202, province:"河北" },
  { name:"赵安易",   dynasty:"金", year:1205, province:"河南" },
  { name:"高守忠",   dynasty:"金", year:1208, province:"山东" },
  { name:"刘浩",     dynasty:"金", year:1211, province:"山西" },
  { name:"李思聪",   dynasty:"金", year:1217, province:"山东" },
  { name:"李演",     dynasty:"金", year:1220, province:"山东" },
  { name:"张格",     dynasty:"金", year:1223, province:"山东" },
  { name:"裴满衡",   dynasty:"金", year:1226, province:"不详" },

  // ── 元 ──
  { name:"张起岩",   dynasty:"元", year:1315, province:"山东" },
  { name:"泰不华",   dynasty:"元", year:1315, province:"不详" },
  { name:"霍希贤",   dynasty:"元", year:1318, province:"山西" },
  { name:"笃列图",   dynasty:"元", year:1318, province:"不详" },
  { name:"宋本",     dynasty:"元", year:1321, province:"河北" },
  { name:"阔里吉思", dynasty:"元", year:1321, province:"不详" },
  { name:"王文烨",   dynasty:"元", year:1324, province:"山东" },
  { name:"忽都达儿", dynasty:"元", year:1324, province:"不详" },
  { name:"朵儿只班", dynasty:"元", year:1327, province:"不详" },
  { name:"普颜不花", dynasty:"元", year:1327, province:"不详" },
  { name:"买闾",     dynasty:"元", year:1330, province:"不详" },
  { name:"脱因",     dynasty:"元", year:1333, province:"不详" },
  { name:"魏元礼",   dynasty:"元", year:1333, province:"不详" },
  { name:"答禄与权", dynasty:"元", year:1335, province:"不详" },
  { name:"只儿哈郎", dynasty:"元", year:1335, province:"不详" },
  { name:"陈祖仁",   dynasty:"元", year:1339, province:"浙江" },
  { name:"朵烈图",   dynasty:"元", year:1342, province:"不详" },
  { name:"成遵",     dynasty:"元", year:1345, province:"河南" },
  { name:"余阙",     dynasty:"元", year:1345, province:"安徽" },
  { name:"大都因帖睦尔", dynasty:"元", year:1348, province:"不详" },
  { name:"王宗哲",   dynasty:"元", year:1351, province:"山东" },
  { name:"唐兀",     dynasty:"元", year:1354, province:"不详" },

  // ── 明 ──
  { name:"吴伯宗",   dynasty:"明", year:1371, province:"江西", city:"抚州市" },
  { name:"丁显",     dynasty:"明", year:1373, province:"福建", city:"南平市" },
  { name:"吴鼎",     dynasty:"明", year:1376, province:"浙江", city:"杭州市" },
  { name:"任亨泰",   dynasty:"明", year:1385, province:"湖北", city:"武汉市" },
  { name:"许观",     dynasty:"明", year:1385, province:"浙江", city:"杭州市" },
  { name:"花纶",     dynasty:"明", year:1385, province:"浙江", city:"杭州市" },
  { name:"练子宁",   dynasty:"明", year:1385, province:"江西", city:"吉安市" },
  { name:"胡广",     dynasty:"明", year:1400, province:"江西", city:"吉安市", county:"吉水县", bio:"胡广（1370—1418年），字光大，号晃庵，吉水（今江西吉水）人。建文二年（1400年）进士第一及第。官至文渊阁大学士。参与编纂《永乐大典》《五经大全》等。擅长书法，为永乐朝重臣。" },
  { name:"王艮",     dynasty:"明", year:1400, province:"江苏", city:"苏州市" },
  { name:"林环",     dynasty:"明", year:1400, province:"福建", city:"莆田市" },
  { name:"曾棨",     dynasty:"明", year:1404, province:"江西", city:"吉安市", county:"永丰县", bio:"曾棨（1372—1432年），字子启，号西墅，永丰（今江西永丰）人。永乐二年（1404年）进士第一及第。工书法，擅诗文，为明代台阁体代表作家。官至詹事府少詹事。" },
  { name:"陈循",     dynasty:"明", year:1404, province:"江西", city:"吉安市" },
  { name:"周述",     dynasty:"明", year:1404, province:"江西", city:"吉安市" },
  { name:"邹缉",     dynasty:"明", year:1404, province:"湖南", city:"衡阳市" },
  { name:"林桥",     dynasty:"明", year:1407, province:"福建", city:"福州市" },
  { name:"萧时中",   dynasty:"明", year:1407, province:"湖南", city:"永州市" },
  { name:"马铎",     dynasty:"明", year:1408, province:"福建", city:"福州市" },
  { name:"林志",     dynasty:"明", year:1411, province:"福建", city:"福州市" },
  { name:"陈全",     dynasty:"明", year:1411, province:"广东", city:"福州市" },
  { name:"梁褧",     dynasty:"明", year:1415, province:"广东", city:"佛山市" },
  { name:"李骐",     dynasty:"明", year:1415, province:"福建", city:"福州市" },
  { name:"陈贯",     dynasty:"明", year:1415, province:"浙江", city:"绍兴市" },
  { name:"郭翀",     dynasty:"明", year:1418, province:"河北", city:"石家庄市" },
  { name:"曾鹤龄",   dynasty:"明", year:1421, province:"江西", city:"吉安市" },
  { name:"洪英",     dynasty:"明", year:1421, province:"浙江", city:"宁德市" },
  { name:"邢宽",     dynasty:"明", year:1424, province:"山西", city:"太原市" },
  { name:"林震",     dynasty:"明", year:1427, province:"福建", city:"漳州市" },
  { name:"曹鼐",     dynasty:"明", year:1427, province:"河北", city:"石家庄市" },
  { name:"赵居任",   dynasty:"明", year:1430, province:"浙江", city:"杭州市" },
  { name:"刘铉",     dynasty:"明", year:1433, province:"浙江", city:"杭州市" },
  { name:"施槃",     dynasty:"明", year:1436, province:"浙江", city:"杭州市" },
  { name:"周旋",     dynasty:"明", year:1439, province:"浙江", city:"温州市" },
  { name:"陈谨",     dynasty:"明", year:1442, province:"福建", city:"福州市" },
  { name:"商辂",     dynasty:"明", year:1450, province:"浙江", city:"淳安县", bio:"商辂（1414—1486年），字弘载，号素庵，严州淳安（今浙江淳安）人。正统十年（1445年）乡试、会试、殿试皆第一，'三元及第'。官至吏部尚书、谨身殿大学士。历事英宗、代宗、宪宗三朝，为明代名臣。卒谥文毅。" },
  { name:"柯潜",     dynasty:"明", year:1454, province:"福建", city:"莆田市" },
  { name:"彭教",     dynasty:"明", year:1457, province:"江西", city:"吉安市" },
  { name:"罗伦",     dynasty:"明", year:1463, province:"江西", city:"吉安市" },
  { name:"张升",     dynasty:"明", year:1466, province:"江西", city:"赣州市" },
  { name:"丁溥",     dynasty:"明", year:1469, province:"浙江", city:"湖州市" },
  { name:"吴宽",     dynasty:"明", year:1472, province:"江苏", city:"苏州市" },
  { name:"谢迁",     dynasty:"明", year:1472, province:"浙江", city:"绍兴市", county:"余姚市", bio:"谢迁（1449—1531年），字于乔，号木斋，余姚（今浙江余姚）人。成化十一年（1475年）进士第一及第。官至兵部尚书、东阁大学士。以直言敢谏闻名，与刘健、李东阳同为弘治朝名相。" },
  { name:"王鏊",     dynasty:"明", year:1475, province:"江苏", city:"苏州市", bio:"王鏊（1450—1524年），字济之，号守溪，吴县（今江苏苏州）人。成化十一年（1475年）进士第一及第。官至户部尚书、文渊阁大学士。博学多才，对《左传》《史记》研究精深。著有《震泽集》。" },
  { name:"李旻",     dynasty:"明", year:1478, province:"浙江", city:"杭州市" },
  { name:"王华",     dynasty:"明", year:1481, province:"浙江", city:"绍兴市", county:"余姚市" },
  { name:"费宏",     dynasty:"明", year:1487, province:"江西", city:"上饶市", county:"铅山县", bio:"费宏（1468—1535年），字子充，号健斋，铅山（今江西铅山）人。成化二十三年（1487年）进士第一及第。官至吏部尚书、华盖殿大学士。历事成化、弘治、正德、嘉靖四朝，为明代名臣。" },
  { name:"钱福",     dynasty:"明", year:1490, province:"江苏", city:"上海市" },
  { name:"毛澄",     dynasty:"明", year:1496, province:"江苏", city:"苏州市" },
  { name:"伦文叙",   dynasty:"明", year:1505, province:"广东", city:"佛山市", county:"南海区", bio:"伦文叙（1467—1513年），字伯畴，号迂冈，南海（今广东佛山南海）人。弘治十二年（1499年）会试、殿试皆第一。官至右春坊右谕德。以才思敏捷著称，广东科举史上的标志性人物。" },
  { name:"朱希周",   dynasty:"明", year:1505, province:"江苏", city:"苏州市" },
  { name:"鲁铎",     dynasty:"明", year:1508, province:"湖北", city:"武汉市" },
  { name:"杨慎",     dynasty:"明", year:1511, province:"四川", city:"成都市", county:"新都区", bio:"杨慎（1488—1559年），字用修，号升庵，新都（今四川成都新都）人。正德六年（1511年）进士第一及第。明代著名学者、文学家。官至翰林院修撰。因'大礼议'事件被贬云南永昌卫，流放三十余年。博览群书，著述宏富，多达百余种。代表作《临江仙·滚滚长江东逝水》《升庵诗话》等。为明代三大才子之首。" },
  { name:"唐皋",     dynasty:"明", year:1514, province:"安徽", city:"黄山市" },
  { name:"孙承恩",   dynasty:"明", year:1517, province:"江苏", city:"苏州市" },
  { name:"储珊",     dynasty:"明", year:1520, province:"浙江", city:"湖州市" },
  { name:"龚用卿",   dynasty:"明", year:1532, province:"福建", city:"福州市" },
  { name:"林大钦",   dynasty:"明", year:1532, province:"广东", city:"潮州市", county:"潮安区", bio:"林大钦（1511—1545年），字敬夫，号东莆，潮州海阳（今广东潮州）人。嘉靖十一年（1532年）进士第一及第。官至翰林院修撰。以才学著称，英年早逝。" },
  { name:"韩应龙",   dynasty:"明", year:1535, province:"浙江", city:"绍兴市" },
  { name:"沈坤",     dynasty:"明", year:1547, province:"江苏", city:"淮安市" },
  { name:"李春芳",   dynasty:"明", year:1547, province:"江苏", city:"扬州市" },
  { name:"秦鸣雷",   dynasty:"明", year:1550, province:"浙江", city:"台州市" },
  { name:"唐汝辑",   dynasty:"明", year:1553, province:"浙江", city:"杭州市" },
  { name:"诸大绶",   dynasty:"明", year:1556, province:"浙江", city:"绍兴市" },
  { name:"申时行",   dynasty:"明", year:1562, province:"江苏", city:"苏州市", bio:"申时行（1535—1614年），字汝默，号瑶泉，吴县（今江苏苏州）人。嘉靖四十一年（1562年）进士第一及第。官至吏部尚书、中极殿大学士（首辅）。万历朝前期主持朝政，宽厚持重。著有《赐闲堂集》。" },
  { name:"陶大临",   dynasty:"明", year:1565, province:"浙江", city:"绍兴市" },
  { name:"丁士美",   dynasty:"明", year:1565, province:"江苏", city:"淮安市" },
  { name:"罗万化",   dynasty:"明", year:1568, province:"浙江", city:"绍兴市" },
  { name:"张元忭",   dynasty:"明", year:1571, province:"浙江", city:"绍兴市" },
  { name:"沈懋学",   dynasty:"明", year:1574, province:"安徽", city:"宣城市" },
  { name:"孙继皋",   dynasty:"明", year:1577, province:"江苏", city:"无锡市" },
  { name:"翁正春",   dynasty:"明", year:1592, province:"福建", city:"福州市" },
  { name:"朱国祚",   dynasty:"明", year:1589, province:"浙江", city:"湖州市" },
  { name:"焦竑",     dynasty:"明", year:1589, province:"江苏", city:"南京市", bio:"焦竑（1540—1620年），字弱侯，号澹园，江宁（今江苏南京）人。万历十七年（1589年）进士第一及第。明代著名学者、藏书家。官至翰林院修撰。博通经史，著述丰富，代表作《国朝献征录》《玉堂丛语》等。" },
  { name:"赵秉忠",   dynasty:"明", year:1598, province:"山东", city:"青州市", bio:"赵秉忠（1573—1626年），字季卿，号■赐，青州府益都县（今山东青州）人。万历二十六年（1598年）进士第一及第。其殿试卷子（状元卷）是目前中国唯一保存完整的明代状元卷真迹，为国家一级文物，现存青州博物馆。" },
  { name:"张以诚",   dynasty:"明", year:1601, province:"浙江", city:"上海市" },
  { name:"杨守勤",   dynasty:"明", year:1604, province:"浙江", city:"宁波市" },
  { name:"黄士俊",   dynasty:"明", year:1607, province:"广东", city:"佛山市", county:"顺德区", bio:"黄士俊（1570—1661年），字亮垣，号玉仑，顺德（今广东佛山顺德）人。万历三十五年（1607年）进士第一及第。官至礼部尚书兼文渊阁大学士。在广东科举史上极具盛名。" },
  { name:"韩敬",     dynasty:"明", year:1610, province:"浙江", city:"湖州市" },
  { name:"周延儒",   dynasty:"明", year:1613, province:"江苏", city:"无锡市" },
  { name:"钱士升",   dynasty:"明", year:1613, province:"浙江", city:"杭州市" },
  { name:"章孔教",   dynasty:"明", year:1616, province:"浙江", city:"温州市" },
  { name:"庄际昌",   dynasty:"明", year:1619, province:"福建", city:"泉州市" },
  { name:"文震孟",   dynasty:"明", year:1622, province:"江苏", city:"苏州市" },
  { name:"余煌",     dynasty:"明", year:1625, province:"浙江", city:"绍兴市" },
  { name:"刘若宰",   dynasty:"明", year:1628, province:"安徽", city:"安庆市" },
  { name:"陈于泰",   dynasty:"明", year:1631, province:"江苏", city:"无锡市" },
  { name:"刘同升",   dynasty:"明", year:1634, province:"江西", city:"吉安市" },
  { name:"刘理顺",   dynasty:"明", year:1637, province:"河南", city:"郑州市" },
  { name:"魏藻德",   dynasty:"明", year:1640, province:"北京", city:"北京市" },
  { name:"陈名夏",   dynasty:"明", year:1640, province:"江苏", city:"南京市" },
  { name:"杨廷鉴",   dynasty:"明", year:1643, province:"江苏", city:"常州市" },

  // ── 清 ──
  { name:"傅以渐",   dynasty:"清", year:1646, province:"山东", city:"聊城市" },
  { name:"吕宫",     dynasty:"清", year:1647, province:"江苏", city:"常州市" },
  { name:"刘子壮",   dynasty:"清", year:1646, province:"湖北", city:"武汉市" },
  { name:"麻勒吉",   dynasty:"清", year:1646, province:"不详" },
  { name:"史大成",   dynasty:"清", year:1649, province:"浙江", city:"宁波市" },
  { name:"邹忠倚",   dynasty:"清", year:1652, province:"江苏", city:"无锡市" },
  { name:"马世俊",   dynasty:"清", year:1652, province:"江苏", city:"镇江市" },
  { name:"黄机",     dynasty:"清", year:1655, province:"浙江", city:"杭州市" },
  { name:"严我斯",   dynasty:"清", year:1658, province:"浙江", city:"湖州市" },
  { name:"徐元文",   dynasty:"清", year:1659, province:"江苏", city:"苏州市" },
  { name:"缪彤",     dynasty:"清", year:1661, province:"江苏", city:"苏州市" },
  { name:"邓中岳",   dynasty:"清", year:1664, province:"山东", city:"聊城市" },
  { name:"张贞生",   dynasty:"清", year:1667, province:"江西", city:"赣州市" },
  { name:"蔡启僔",   dynasty:"清", year:1670, province:"浙江", city:"湖州市" },
  { name:"韩菼",     dynasty:"清", year:1673, province:"江苏", city:"苏州市" },
  { name:"彭定求",   dynasty:"清", year:1676, province:"江苏", city:"苏州市" },
  { name:"归允肃",   dynasty:"清", year:1679, province:"江苏", city:"苏州市" },
  { name:"蔡升元",   dynasty:"清", year:1685, province:"浙江", city:"湖州市" },
  { name:"陆肯堂",   dynasty:"清", year:1685, province:"江苏", city:"苏州市" },
  { name:"陈敬",     dynasty:"清", year:1685, province:"山西" },
  { name:"戴有祺",   dynasty:"清", year:1688, province:"江苏", city:"上海市" },
  { name:"胡任舆",   dynasty:"清", year:1688, province:"江苏", city:"南京市" },
  { name:"卢楞伽",   dynasty:"清", year:1688, province:"广东" },
  { name:"李蟠",     dynasty:"清", year:1697, province:"江苏", city:"徐州市" },
  { name:"汪绎",     dynasty:"清", year:1700, province:"江苏", city:"苏州市" },
  { name:"王式丹",   dynasty:"清", year:1700, province:"江苏", city:"扬州市" },
  { name:"王世琛",   dynasty:"清", year:1703, province:"江苏", city:"苏州市" },
  { name:"赵熊诏",   dynasty:"清", year:1703, province:"江苏", city:"常州市" },
  { name:"缪沅",     dynasty:"清", year:1706, province:"江苏", city:"苏州市" },
  { name:"王敬铭",   dynasty:"清", year:1709, province:"江苏", city:"上海市" },
  { name:"赵晋",     dynasty:"清", year:1712, province:"江苏", city:"南京市" },
  { name:"王云锦",   dynasty:"清", year:1715, province:"江苏", city:"无锡市" },
  { name:"徐陶璋",   dynasty:"清", year:1718, province:"江苏", city:"苏州市" },
  { name:"邓钟岳",   dynasty:"清", year:1721, province:"山东", city:"聊城市" },
  { name:"于振",     dynasty:"清", year:1724, province:"江苏", city:"南京市" },
  { name:"陈德华",   dynasty:"清", year:1727, province:"河北", city:"石家庄市" },
  { name:"彭启丰",   dynasty:"清", year:1727, province:"江苏", city:"苏州市" },
  { name:"周澍",     dynasty:"清", year:1730, province:"浙江", city:"杭州市" },
  { name:"徐本",     dynasty:"清", year:1733, province:"浙江", city:"杭州市" },
  { name:"金德瑛",   dynasty:"清", year:1736, province:"浙江", city:"杭州市" },
  { name:"于敏中",   dynasty:"清", year:1745, province:"江苏", city:"苏州市" },
  { name:"钱维城",   dynasty:"清", year:1745, province:"江苏", city:"扬州市" },
  { name:"庄有恭",   dynasty:"清", year:1748, province:"广东", city:"广州市" },
  { name:"沈初",     dynasty:"清", year:1748, province:"浙江", city:"嘉兴市" },
  { name:"秦大士",   dynasty:"清", year:1751, province:"江苏", city:"南京市" },
  { name:"庄培因",   dynasty:"清", year:1754, province:"江苏", city:"苏州市" },
  { name:"梁国治",   dynasty:"清", year:1754, province:"浙江", city:"绍兴市" },
  { name:"蔡以台",   dynasty:"清", year:1757, province:"浙江", city:"嘉兴市" },
  { name:"庄存与",   dynasty:"清", year:1757, province:"江苏", city:"苏州市" },
  { name:"毕沅",     dynasty:"清", year:1760, province:"江苏", city:"苏州市", county:"太仓市", bio:"毕沅（1730—1797年），字纕蘅，号秋帆，镇洋（今江苏太仓）人。乾隆二十五年（1760年）进士第一及第。官至湖广总督。清代著名学者、藏书家。主持编纂《续资治通鉴》，于经学、史学、地理学均有精深研究。" },
  { name:"王杰",     dynasty:"清", year:1760, province:"陕西", city:"韩城市", bio:"王杰（1725—1805年），字伟人，号惺园，韩城（今陕西韩城）人。乾隆二十六年（1761年）进士第一及第。官至东阁大学士（首辅）。为官清正，刚直不阿。陕西在清朝唯一的状元。" },
  { name:"秦大成",   dynasty:"清", year:1763, province:"江苏", city:"上海市" },
  { name:"张书勋",   dynasty:"清", year:1766, province:"江苏", city:"苏州市" },
  { name:"陈初哲",   dynasty:"清", year:1769, province:"江苏", city:"苏州市" },
  { name:"钱棨",     dynasty:"清", year:1778, province:"江苏", city:"苏州市" },
  { name:"吴锡龄",   dynasty:"清", year:1772, province:"安徽", city:"黄山市" },
  { name:"金榜",     dynasty:"清", year:1771, province:"安徽", city:"黄山市" },
  { name:"茹棻",     dynasty:"清", year:1784, province:"浙江", city:"绍兴市" },
  { name:"史致光",   dynasty:"清", year:1784, province:"浙江", city:"绍兴市" },
  { name:"汪如洋",   dynasty:"清", year:1787, province:"浙江", city:"嘉兴市" },
  { name:"石韫玉",   dynasty:"清", year:1790, province:"江苏", city:"苏州市" },
  { name:"胡长龄",   dynasty:"清", year:1790, province:"江苏", city:"南通市" },
  { name:"潘世恩",   dynasty:"清", year:1793, province:"江苏", city:"苏州市", bio:"潘世恩（1770—1854年），字槐堂，号芝轩，吴县（今江苏苏州）人。乾隆五十八年（1793年）进士第一及第。官至军机大臣兼翰林院掌院学士。历仕乾隆、嘉庆、道光、咸丰四朝，位极人臣。卒谥文恭。" },
  { name:"赵文楷",   dynasty:"清", year:1796, province:"安徽", city:"安庆市" },
  { name:"姚文田",   dynasty:"清", year:1799, province:"浙江", city:"杭州市" },
  { name:"顾皋",     dynasty:"清", year:1799, province:"江苏", city:"无锡市" },
  { name:"吴廷琛",   dynasty:"清", year:1802, province:"江苏", city:"苏州市" },
  { name:"彭浚",     dynasty:"清", year:1802, province:"湖南", city:"衡阳市" },
  { name:"吴信中",   dynasty:"清", year:1805, province:"江苏", city:"苏州市" },
  { name:"蒋立镛",   dynasty:"清", year:1808, province:"湖北", city:"天门市" },
  { name:"龙汝言",   dynasty:"清", year:1809, province:"安徽", city:"安庆市" },
  { name:"陈鋆",     dynasty:"清", year:1811, province:"浙江", city:"杭州市" },
  { name:"蒋元溥",   dynasty:"清", year:1814, province:"浙江", city:"杭州市" },
  { name:"吴其浚",   dynasty:"清", year:1817, province:"河南", city:"信阳市" },
  { name:"陈大汶",   dynasty:"清", year:1820, province:"浙江", city:"金华市" },
  { name:"钮福保",   dynasty:"清", year:1823, province:"江苏", city:"苏州市" },
  { name:"林召棠",   dynasty:"清", year:1823, province:"广东", city:"湛江市" },
  { name:"朱昌颐",   dynasty:"清", year:1826, province:"浙江", city:"嘉兴市" },
  { name:"戴兰芬",   dynasty:"清", year:1826, province:"安徽", city:"合肥市" },
  { name:"吴钟骏",   dynasty:"清", year:1832, province:"江苏", city:"苏州市" },
  { name:"刘绎",     dynasty:"清", year:1832, province:"江西", city:"吉安市" },
  { name:"钟骏声",   dynasty:"清", year:1835, province:"浙江", city:"杭州市" },
  { name:"林鸿年",   dynasty:"清", year:1835, province:"福建", city:"福州市" },
  { name:"李承霖",   dynasty:"清", year:1838, province:"江苏", city:"镇江市" },
  { name:"张启恩",   dynasty:"清", year:1838, province:"山东" },
  { name:"胡家玉",   dynasty:"清", year:1841, province:"江西" },
  { name:"潘祖荫",   dynasty:"清", year:1844, province:"江苏", city:"苏州市" },
  { name:"萧锦忠",   dynasty:"清", year:1844, province:"湖南", city:"长沙市" },
  { name:"苑广文",   dynasty:"清", year:1847, province:"山东" },
  { name:"张之万",   dynasty:"清", year:1847, province:"河北", city:"沧州市", county:"南皮县", bio:"张之万（1811—1897年），字子青，号銮坡，直隶南皮（今河北南皮）人。道光二十七年（1847年）进士第一及第。官至体仁阁大学士、军机大臣。其弟张之洞为晚清名臣。以书法闻名。" },
  { name:"陆增祥",   dynasty:"清", year:1850, province:"江苏", city:"苏州市" },
  { name:"孙如仅",   dynasty:"清", year:1853, province:"山东", city:"济南市" },
  { name:"孙家鼐",   dynasty:"清", year:1856, province:"安徽", city:"滁州市", county:"寿县", bio:"孙家鼐（1827—1909年），字燮臣，号蛰生，寿州（今安徽寿县）人。咸丰九年（1859年）进士第一及第。官至武英殿大学士、资政院总裁。晚清重臣，支持洋务运动和维新变法。创办京师大学堂（北京大学前身）。" },
  { name:"翁同龢",   dynasty:"清", year:1856, province:"江苏", city:"苏州市", county:"常熟市", bio:"翁同龢（1830—1904年），字声甫，号叔平，常熟（今江苏常熟）人。咸丰六年（1856年）进士第一及第。官至户部尚书、协办大学士、军机大臣。先后担任同治、光绪两帝师傅。支持维新变法，为帝党领袖。工书法，为同治、光绪年间书坛盟主。" },
  { name:"翁曾源",   dynasty:"清", year:1859, province:"江苏", city:"苏州市", county:"常熟市" },
  { name:"章鋆",     dynasty:"清", year:1859, province:"浙江", city:"宁波市" },
  { name:"徐郙",     dynasty:"清", year:1865, province:"江苏", city:"苏州市" },
  { name:"洪钧",     dynasty:"清", year:1868, province:"江苏", city:"苏州市", bio:"洪钧（1839—1893年），字陶士，号文卿，吴县（今江苏苏州）人。同治七年（1868年）进士第一及第。官至兵部左侍郎兼总理各国事务衙门大臣。晚清外交家，曾出使俄、德、奥、荷四国。著有《元史译文证补》。其妾赵彩云（赛金花）为近代传奇人物。" },
  { name:"梁耀枢",   dynasty:"清", year:1868, province:"广东", city:"广州市" },
  { name:"梅启照",   dynasty:"清", year:1871, province:"安徽" },
  { name:"陆润庠",   dynasty:"清", year:1874, province:"江苏", city:"苏州市", bio:"陆润庠（1841—1915年），字凤石，号云洒，元和（今江苏苏州）人。同治十三年（1874年）进士第一及第。官至东阁大学士、弼德院院长。清朝最后一位去世的状元。工书法。民国后以遗老自居。" },
  { name:"曹鸿勋",   dynasty:"清", year:1877, province:"山东", city:"潍坊市", bio:"曹鸿勋（1848—1910年），字仲铭，号兰生，潍县（今山东潍坊）人。光绪二年（1876年）进士第一及第。官至陕西巡抚。在陕西任内兴办教育、整顿吏治。擅长书法。" },
  { name:"王仁堪",   dynasty:"清", year:1877, province:"福建", city:"福州市" },
  { name:"黄思永",   dynasty:"清", year:1880, province:"江苏", city:"南京市" },
  { name:"黎培敬",   dynasty:"清", year:1880, province:"湖南", city:"湘潭市" },
  { name:"陈冕",     dynasty:"清", year:1880, province:"浙江" },
  { name:"崔国因",   dynasty:"清", year:1880, province:"安徽" },
  { name:"于式枚",   dynasty:"清", year:1880, province:"广西", city:"南宁市" },
  { name:"赵以炯",   dynasty:"清", year:1886, province:"贵州", city:"贵阳市", county:"花溪区", bio:"赵以炯（1857—1907年），字仲莹，号鹤林，贵阳青岩（今贵州贵阳花溪）人。光绪十二年（1886年）进士第一及第。贵州历史上第一位（也是唯一一位）文状元。官至翰林院编撰、云南学政。是贵州科举史上的标志性人物。" },
  { name:"吴鲁",     dynasty:"清", year:1886, province:"福建", city:"泉州市" },
  { name:"张建勋",   dynasty:"清", year:1889, province:"广西", city:"桂林市" },
  { name:"李盛铎",   dynasty:"清", year:1889, province:"江西", city:"南昌市" },
  { name:"刘福姚",   dynasty:"清", year:1892, province:"广西", city:"桂林市" },
  { name:"张謇",     dynasty:"清", year:1894, province:"江苏", city:"南通市", county:"海门区", bio:"张謇（1853—1926年），字季直，号啬庵，江苏海门（今南通海门）人。光绪二十年（1894年）进士第一及第。晚清民初著名实业家、教育家。主张'实业救国'，创办大生纱厂等数十家企业，构建了中国近代民族工业体系。兴办学校、图书馆、博物馆等，是中国近代化的重要先驱。" },
  { name:"骆成骧",   dynasty:"清", year:1895, province:"四川", city:"资阳市" },
  { name:"夏同龢",   dynasty:"清", year:1898, province:"贵州", city:"贵阳市" },
  { name:"王寿彭",   dynasty:"清", year:1903, province:"山东", city:"济南市" },
  { name:"刘春霖",   dynasty:"清", year:1904, province:"河北", city:"沧州市", county:"肃宁县", bio:"刘春霖（1872—1944年），字润琴，号石云，直隶肃宁（今河北肃宁）人。光绪三十年（1904年）进士第一及第。中国历史上最后一位科举状元。清末被派往日本留学。民国后隐居不仕，以鬻字为生。工书法，尤精小楷。1944年病逝于北平。" },
];

module.exports = ZHUANGYUAN_DATA;
